[project]
name = "backend"
version = "0.1.0"
description = "The API backend for inventory-lab"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "sqlalchemy>=2.0.43",
]
